version: '3.9'

services:
  todo-app:
    build:
      context: ./
    command: ./todo-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=666

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD = 666
      - POSTGRES_USER = postgres
      - POSTGRES_DB = postgres
    ports:
      - "5433:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
  migrate:
    container_name: migrate
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./schema:/migrations
    command: [
        "-path", "/migrations", "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable", "up"
      ]

