version: '3.8'

services:
  todo-app:
    build: ./
    command: ./todo-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=666
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=666
    ports:
      -   "5433:5432"

