CREATE TABLE public.users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL
);
CREATE TABLE public.todo_lists (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            title VARCHAR(255) NOT NULL,
                            description VARCHAR(255)
);
CREATE TABLE public.users_lists (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT NOT NULL,
                             list_id BIGINT NOT NULL,
                             FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
                             FOREIGN KEY (list_id) REFERENCES public.todo_lists(id) ON DELETE CASCADE
);
CREATE TABLE public.todo_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            title VARCHAR(255) NOT NULL,
                            description VARCHAR(255),
                            done BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE public.lists_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             item_id BIGINT NOT NULL,
                             list_id BIGINT NOT NULL,
                             FOREIGN KEY (item_id) REFERENCES public.todo_items(id) ON DELETE CASCADE,
                             FOREIGN KEY (list_id) REFERENCES public.todo_lists(id) ON DELETE CASCADE
);
